### ISSUE TITLE
Interest Based Advertising with the Topics API

### ISSUE THREAD

**Issue by jkarlin** [patcg/proposals#4]
**Problem** 
With the upcoming removal of third-party cookies on the web, key use cases that browsers want to support will need to be addressed with new APIs. One of those use cases is interest-based advertising.

Interest-based advertising (IBA) is a form of personalized advertising in which an ad is selected for the user based on interests derived from the sites that they’ve visited in the past. This is different from contextual advertising, which is based solely on the interests derived from the current site being viewed (and advertised on). One of IBA’s benefits is that it allows sites that are useful to the user, but perhaps could not be easily monetized via contextual advertising, to display more relevant ads to the user than they otherwise could, helping to fund the sites that the user visits.

**Proposal Summary**
The intent of the [Topics API](https://github.com/jkarlin/topics) is to provide callers (including third-party ad-tech or advertising providers on the page that run script) with coarse-grained advertising topics that the page visitor might currently be interested in. These topics will supplement the contextual signals from the current page and can be combined to help find an appropriate advertisement for the visitor.

The topics are selected from an advertising taxonomy. The initial taxonomy (proposed for experimentation) will include somewhere between a few hundred and a few thousand topics and will attempt to exclude sensitive topics. The eventual goal is for the taxonomy to be sourced from an external party that incorporates feedback and ideas from across the industry.

The topics will be inferred by the browser. The browser will leverage a classifier model to map site hostnames to topics. The classifier weights will be public, perhaps built by an external partner, and will improve over time. The browser will share up to 1 frequently visited topic (by the user) from each of the past 3 weeks to share with callers on a given site.

**Comment by seanturner** [comment]
@jkarlin An option to get this work consider by the patcg is to move the work into this [proposals repo](https://github.com/patcg/proposals). To be precise, I think that a link is not sufficient you can either a) create a folder for the two drafts the proposals repo or b) create one git submodule for both drafts if you want to continue managing them for now in your own repo. The W3C CLA would then apply in either case; see [proposal workflow](https://github.com/patcg/proposals#proposal-workflow).

**Comment by AramZS** [comment]
(Quick note @jkarlin - you have been invited to have `write` access to this repository in order to support this process)

**Comment by jkarlin** [comment]
Thank you for the suggestions! I think it's important that we have a separate repository for issues tracking though, as there are quite a few.

**Comment by jyasskin** [comment]
Note that https://github.com/patcg/proposals#what-happens-next anticipates the chairs creating a repository for a proposal before it's adopted as a work item. Another similar CG, https://privacycg.github.io/charter.html#proposals, says "Champions may ask the Chairs to create a dedicated repository for their Proposal. The Chairs will generally honor such requests…"

**Comment by martinthomson** [comment]
I consider the README to be in error here.  While other CGs do provide repositories for proposals, that creates a false impression that this is an official product of this CG.  This is a problem with Privacy CG, which is shared by WICG also.

It turns out that your personal repository (or any org in which you might choose to house a respository) works perfectly well for tracking issues with proposals.

What doesn't work very well is discussion of general topics, which is what we should be doing in the absence of a single chosen work product.  For that, I suggest we create a generic repository - with no content - that we can use for discussions of a specific topic (no pun intended), in this case interest-based targeting.  There we can talk about this proposal and its relationship to our principles or to other proposals (Ad Topic Hints, for instance).

That indicates another advantage of keeping the work in a private repository until this group decides what to do with it: it ensures that people can watch the repository and participate in higher-level discussions without having to filter out the churn associated with refinement of the text of the proposal.  As long as there are multiple competing proposals, that's an amplification factor many of us might prefer not to deal with.

**Comment by michaelkleber** [comment]
Hello folks.  We need some resolution here — we have people who would like to contribute to the Topics incubation and discussion, but are unable to do so until it's covered appropriate IP licensing guarantees.

It seems like there are two disagreeing schools of thought:

1. Incubate inside some within-PATCG sub-repository, as suggested by the Charis above and described in the CG's [Proposal workflow](https://github.com/patcg/proposals#proposal-workflow).  As Martin points out, this risks confusion about to what extent the CG has endorsed this solution rather than agreed to discuss the problem space.

2. Host a discussion in PATCG about the general problem space, with the generic repository that Martin suggests.  At the same time, continue to incubate Topics in some other venue that provides W3C IPR coverage — the natural choice seems like WICG, which is already hosting FLoC (whose incubation gave rise to Topics in the first place).

We can move forward with either model.  But some consensus on how incubation ought to work seems rather important.

**Comment by dmarti** [comment]
WICG seems to have worked fine for FLoC so far. It looks like WICG would be an appropriate place for Topics too.

**Comment by darobin** [comment]
I would rather everything be here instead of scattered all over. People often ask "what's happening in new ad standards" and there is nowhere to point them; I don't see value in making the space even harder to track than it already is (I don't think we should prevent tracking _that_ hard). I also don't really buy the "impression of endorsement" argument, I don't think that the PATCG will make anything look more endorsed to folks who can't already tell the difference. I think that, for folks who understand shades of endorsement, we can clearly communicate the status of the document.

**Comment by eriktaubeneck** [comment]
> It turns out that your personal repository (or any org in which you might choose to house a respository) works perfectly well for tracking issues with proposals.

It seems that there are reasonable concerns around the impact of this suggestion on IP considerations. Specifically, it skips the step outlined in the CG's proposal workflow (as @michaelkleber points out):

> **Join the group**. Before making a proposal, please [join the CG](https://www.w3.org/community/patcg/join). This is to ensure that all contributions to our work are covered by the [W3C Community Contributor License Agreement (CLA)](https://www.w3.org/community/about/agreements/cla/).

IANAL, so I won't comment on any actual difference between including it within this repo or elsewhere, but given that some have concern here, it seems reasonable to want to have these contributions within a W3C repo.

Given that, the question seems to reduce to which group should it live in, PATCG or another group like the WICG. For proposals related to *private advertising*, it seems to me the PATCG would be preferable.

To @darobin's suggestion
> we can clearly communicate the status of the document.

I would further suggest possibly making the title of the repo `proposal-<name>` for proposals, and `workitem-<name>` for adopted work items.

**Comment by bmayd** [comment]
I agree with @darobin suggests both about not scattering things (it would be great if PATCG was the center of this universe) and regarding the suggestion of endorsement (we're talking about Topics now, which at some level is an endorsement of it). However, I supported @martinthomson suggestion out of concern for what happens to proposals like Topics if they're included in the PATCG repository and this community decides not to move forward with them, but the proposer wants to continue to pursue them. From that perspective it seemed to me it would be best to keep things separate until we're confident we want to take them on.

**Comment by michaelkleber** [comment]
@bmayd That's an interesting consideration.  I think it would be straightforward to migrate a repo _out_ of PATCG in the same way that we're now talking about migrating one _in,_ so this doesn't feel like a risk to me.  But if you know of some bad experience like this, feel free to burst my optimistic bubble.

**Comment by bmayd** [comment]
I was thinking more in terms of avoiding confusion and disruptions to the efforts to pursue the proposal; loss of focus, momentum, coordination, wear and tear on folks, etc., than of technical difficulty or risks of a migration. It has an established home and it seems before moving it we would do well to be reasonably confident we're going to commit to supporting it.

**Comment by alextcone** [comment]
I'm pro consolidation to PATCG (ala @darobin) and pro prioritization of things likely to get multiple implementers (ala @martinthomson, @benjaminsavage, etc). Given that Chrome seems to be moving forward whether there are other implementers of its proposals are not, I think we should weigh that in our considerations of what gets focus and when. 

A few general notes on Topics that I think have people hesitant to prioritize for standards outside of Chrome:

- it has the appearance, whether fair or not, of the browser taking on, proactively, the role typically most associated with a data marketplace (whereas facilitating measurement and arbitrary interest groups by practitioners sits a bit different) 
- It disrupts some browsers' business models so there's likely to remain an unsupportive element there.
- it feels more experimental than attribution measurement or interest groups defined by practitioners. Where as the latter _must_ work, Topics can get by with working here and there as an advertiser wants to test a Topic in their overall mix

**Comment by martinthomson** [comment]
> we can clearly communicate the status of the document.

This does not work in my experience.  At all.  Hence my objection.

We have a process for adoption for which the bar is consensus.  That's the standard we need to meet.  I don't agree that moving out is that simple.

I am not a lawyer, but my understanding is that any repository can establish contribution guidelines that ensure IPR requirements are met, if that is the prevailing concern.

**Comment by braedon** [comment]
An anecdote on using personal repos - I've gone to read up on a new proposals and ended up on personal repos multiple times. It's always been confusing and unclear whether I've actually found *the* proposal, or someone's (unlinked) clone.

**Comment by darobin** [comment]
>> we can clearly communicate the status of the document.
>
> This does not work in my experience. At all. Hence my objection.

I am keenly aware of the problem you are describing, but I don't think that your solution to it works. There are two constituencies to consider. On the one hand are people who don't understand that discussing something is different from adopting. For that constituency, whether you say "This is only a proposal for discussion." at the top, or whether you store it at https://github.com/darobin-personal-account-go-away/personal-karaoke-notes/blob/dangerous-experimental-branch/stupider-ideas/DO-NOT-READ-THIS.md with a blinking marquee of capybaras at the top singing _Never got no con-sen-sus, Never gonna imp-le-ment_ it will _still_ get breathlessly described as "_The New York Times hates the Web, is going to lock up donkeys in the privacy sandbox._" Case in point: Topics is a Markdown file in a personal GitHub repo and it still got picked up as basically _fait accompli_ on the Web.

The other constituency is folks who'll pay attention to the distinction. I think we should optimise for this group, not because they matter more but because we know how to solve this.

**Comment by AramZS** [comment]
I hear both sides of this discussion, which I think mirror my two positions of thought as well. On one hand it has been clear that one of the flaws of the PrivacyCG's process in this regard has been that pulling in repos have given particular proposals a legitimacy that does not reflect their actual status within the W3C process *to people outside of that process*. But I agree that, since this group has **decided** this proposal is *of interest* it would be better to centralize our resources. I also hear the objection that making it a sub repo in this space makes issues difficult to manage. I'm still not sure that's the case, we can provide specific labels etc... but if the maintainer feels that this is too large of a barrier to maintenance I can understand that as well. I also agree with @darobin's point that even *not* putting it in a CG GitHub org can still result in folks outside the space misunderstanding the process. 

So, I believe the best approach right now is, if the maintainer strongly feels that they need their own repo, we determine the appropriate language to amend the README here and to add to any README of a project that enters our GitHub org to make it as clear as possible that our (the PATCG's) interest in facilitating discussion under the W3C rules of conduct and W3C CLA does not constitute this group **necessarily** moving it forward into a specification or formal report even if that may eventually be one of the actions we choose to take at some point in the future. W3C rules and our Charter would seem to mechanically allow for this, so I think the core issue is making such a thing clear in language here and on the subject repo. 

I stress that this process would not be for every proposal in the world, but only for those that the group chooses to take up in this way and facilitate, as subject to the consensus process in either meeting or GitHub thread.

**Comment by AramZS** [comment]
Additionally, as an added measure of clarity, we can specifically have these moved repos also included as GitHub submodules in this repo as long as they are in this intermediate state, to make their status clear. If we can come up with language that makes this process clear @martinthomson do you think we can come to a way to bring this repo into this org?

**Comment by dmarti** [comment]
@AramZS Making a separate area for proposals that are at an early state seems like <q>a lightweight venue for proposing and discussing new web platform features</q> which is [what WICG is already set up to do](https://wicg.github.io/admin/charter.html). I don't understand why this group would need to make its own WICG-like area and associated documentation changes when there is already a WICG, and the previous version of this proposal is [still there](https://github.com/WICG/floc).

**Comment by bmayd** [comment]
@dmarti makes a good point: it makes sense to use an existing venue and tooling if we can. I suppose we’d want some way of signaling that PATCG is considering such early stage proposals and a directory listing the proposals we’ve considered, their status within this group and appropriate links.
 
Beyond that, I think we would do well to clearly and concisely articulate the criteria and conditions for adding and removing proposals from PATCG, regardless of how things are ultimately structured, including obligations and limitations that must be agreed to before bringing a proposal to this group, and particularly those which survive the removal of a proposal from consideration.

I also think we would do well to be sensitive to the cognitive burden we place on the members of PATCG, many of whom are chronically over extended as they struggle to keep up with the mounting tide of activity in the space; much as we might want PATCG to be the center of our universe, it no doubt will always be one of many. So, the more we can do to structure things in ways that reduce the effort to engage (like maintaining a directory of work, separating active proposals from inactive and consistently and concisely noting why we’ve decided a proposal will not be pursued), the more productive we will be and the more likely we are to engage domain experts from the broader community whose help we badly need and many of who are only able to make a casual commitment to the work.

**Comment by dmarti** [comment]
@bmayd Yes, that makes sense. We can maintain a page here in this repository with links to early stage proposals at WICG and other locations.

**Comment by AramZS** [comment]
I do see that mandate in WICG, though I personally find the fracturing of proposals that are arguably directly related to our mission difficult to manage and have heard that complaint from others. I can see the solution @bmayd suggests making sense, but my sense is that @martinthomson's objections are just as valid if the proposal enters WICG as it is if it enters here. So I'm not sure that having it noted here and living in WICG is any more fairly addressing his concern, just sort of moving it out of our domain. (Unless @martinthomson says otherwise) As @ekr noted in the meeting:

> But we need a word for “work item for the group”, not just a thing being talked about.

And it seems to me the lack of that being established as something significantly different from "intended to become a Community Group Report" is going to be a recurring problem? Better to resolve it in such a way that we feel it settles this case not just as a one-off but as a process if we can? 

I will note that having it in this repo as a submodule would make it a clear candidate for discussion without portending a more formal state. It would also give it a clear and easy to use link and note the current repo as the "official" repository that can help sort the confusion about personal repositories while giving it its own issues and space in it's current location. Then, should that space progress the proposal to a state where we have consensus that it is ready to become the subject of a formal report, we can bring it in as a full repo inside the PATCG org. I think then the only thing we need is to assure the language makes this process clear in the README here, and, if people feel the charter doesn't sufficiently cover this use case, we could discuss an amendment.

**Comment by wseltzer** [comment]
Without expressing an opinion whether PATCG should work on Topics AP long-term, a few points from a W3C team legal perspective: 
* The [W3C Community CLA](https://www.w3.org/community/about/process/cla/) provides a framework for contribution commitments in a CG. While it doesn't mandate where that CG's work is done, some practices such as the group-participant [IPR-checker](https://github.com/w3c/ash-nazg) are facilitated by connecting repositories to the CG. 
* Similarly, some organizations' legal review is facilitated by grouping work, even preliminary work, in one CG
* W3C wants to provide fora for both incubation and specification, where the incubation process may lead down dead ends before finding the path to consensus. We try to reduce the barriers to starting incubation work (open to the public, lightweight CG process) to give ideas and their proponents opportunity for an early hearing and iterative development before sending them to a WG for spec development.

**Comment by AramZS** [comment]
After some consideration, I have authored an alteration to the charter that I hope will allow us to have incubation handled internally as makes sense for facilitating that work within the fairly unique constituency interested in private advertising technology. The PR is up for review and I would appreciate feedback from participants in this thread:

https://github.com/patcg/patcg.github.io/pull/7 

Hopefully, we can merge this change and then move forward on this issue by considering the proposal in "incubation" under the proposed new process.

**Comment by michaelkleber** [comment]
Thank you @AramZS, this seems well thought out.  Chrome is supportive.

**Comment by dmarti** [comment]
@AramZS The Topics API proposal is still sufficiently problematic&mdash;structured to favor large, general interest and UGC sites, and put niche sites with one or a few topics at a disadvantage&mdash;that it is not ready for incubation yet. I understand that incubation is an appropriate place for proposals that are a step in the right direction. It would not really be productive to do group discussion of this proposal until this obvious problem is addressed, and incubating this proposal would send the wrong message to authors of future proposals.

**Comment by AramZS** [comment]
We now have [an individual drafts space](https://github.com/patcg-individual-drafts) as agreed upon in the charter. @jkarlin you should now have an invite to become a member of that GitHub org. Once you accept, you should have the right privileges to add your repository to that space. With this new process in place, this issue is resolved. @jkarlin Once you have moved the repository into the new space, you can inform this thread and close the issue. Thanks!

**Comment by jkarlin** [comment]
Transferred. Thanks folks!
